CREATE TABLE INDICADO 
(
  codindicado NUMBER NOT NULL 
, descripcion VARCHAR2(50) NOT NULL 
, valorminimoaceptado NUMBER NOT NULL 
, codarea NUMBER NOT NULL 
, CODEMP NUMBER NOT NULL 
, funcion VARCHAR2 (100) NOT NULL
, valoresperado NUMBER NOT NULL
, codent NUMBER NOT NULL
, CONSTRAINT INDICADO_PK PRIMARY KEY 
  (
    codindicado 
  )
);

CREATE SEQUENCE INDICADO_SEQ INCREMENT BY 1 START WITH 1 MAXVALUE 99999999999999999999 MINVALUE 1 NOCACHE;


CREATE TABLE GRUPOIN 
(
  codgrupoin NUMBER NOT NULL 
, descripcion VARCHAR2(50) NOT NULL 
, codindicado NUMBER NOT NULL 
, codent NUMBER NOT NULL
, CONSTRAINT GRUPOIN_PK PRIMARY KEY 
  (
    codgrupoin 
  )
);

CREATE SEQUENCE GRUPOIN_SEQ INCREMENT BY 1 START WITH 1 MAXVALUE 99999999999999999999 MINVALUE 1 NOCACHE;


CREATE TABLE GRUPOEM 
(
  codgrupoem NUMBER NOT NULL 
, CODEMP NUMBER NOT NULL 
, activo VARCHAR2(1) NOT NULL
, codent NUMBER NOT NULL
, CONSTRAINT GRUPOEM_PK PRIMARY KEY 
  (
    codgrupoem 
  )
);

CREATE SEQUENCE GRUPOEM_SEQ INCREMENT BY 1 START WITH 1 MAXVALUE 99999999999999999999 MINVALUE 1 NOCACHE;

CREATE TABLE RESUINDI 
(
  codresuindi NUMBER NOT NULL 
, ano NUMBER NOT NULL 
, mes VARCHAR2(50) NOT NULL
, valorindicador NUMBER NOT NULL 
, justificacion VARCHAR2(50) NOT NULL
, planaccionmejora VARCHAR2(50) NOT NULL
, codent NUMBER NOT NULL
, CODINDICADO NUMBER NOT NULL 
, CONSTRAINT RESUINDI_PK PRIMARY KEY 
  (
    codresuindi 
  )
);

CREATE SEQUENCE RESUINDI_SEQ INCREMENT BY 1 START WITH 1 MAXVALUE 99999999999999999999 MINVALUE 1 NOCACHE;


ALTER TABLE GRUPOIN ADD CONSTRAINT FK_GRUPOIN_INDICADO FOREIGN KEY (CODINDICADO) REFERENCES INDICADO(CODINDICADO);
ALTER TABLE RESUINDI ADD CONSTRAINT FK_RESUINDI_INDICADO FOREIGN KEY (CODINDICADO) REFERENCES INDICADO(CODINDICADO);
ALTER TABLE GRUPOEM ADD CONSTRAINT FK_GRUPOEM_GRUPOIN FOREIGN KEY (CODGRUPOIN) REFERENCES GRUPOIN(CODGRUPOIN);
ALTER TABLE INDICADO ADD CONSTRAINT FK_INDICADO_EMPLEADO FOREIGN KEY (CODEMP) REFERENCES TIMCON.EMPLEADO(CODEMP);
ALTER TABLE GRUPOEM ADD CONSTRAINT FK_GRUPOEM_EMPLEADO FOREIGN KEY (CODEMP) REFERENCES TIMCON.EMPLEADO(CODEMP);
ALTER TABLE INDICADO ADD CONSTRAINT FK_INDICADO_AREA FOREIGN KEY (AREAID) REFERENCES TIMCON.AREA(AREAID);